import colorPalette from '@src/tokens/colorPalette'
import { StitchesColors } from '../types'

// TODO: type auto generate primary, secondary...

const themeColor: StitchesColors = {
  transparent: colorPalette.transparent,
  current: colorPalette.current,
  black: colorPalette.black,
  white: colorPalette.white,

  primary1: colorPalette.purple.purple1,
  primary2: colorPalette.purple.purple2,
  primary3: colorPalette.purple.purple3,
  primary4: colorPalette.purple.purple4,
  primary5: colorPalette.purple.purple5,
  primary6: colorPalette.purple.purple6,
  primary7: colorPalette.purple.purple7,
  primary8: colorPalette.purple.purple8,
  primary9: colorPalette.purple.purple9,
  primary10: colorPalette.purple.purple10,
  primary11: colorPalette.purple.purple11,
  primary12: colorPalette.purple.purple12,

  primaryA1: colorPalette.purpleA.purpleA1,
  primaryA2: colorPalette.purpleA.purpleA2,
  primaryA3: colorPalette.purpleA.purpleA3,
  primaryA4: colorPalette.purpleA.purpleA4,
  primaryA5: colorPalette.purpleA.purpleA5,
  primaryA6: colorPalette.purpleA.purpleA6,
  primaryA7: colorPalette.purpleA.purpleA7,
  primaryA8: colorPalette.purpleA.purpleA8,
  primaryA9: colorPalette.purpleA.purpleA9,
  primaryA10: colorPalette.purpleA.purpleA10,
  primaryA11: colorPalette.purpleA.purpleA11,
  primaryA12: colorPalette.purpleA.purpleA12,

  secondary1: colorPalette.cyan.cyan1,
  secondary2: colorPalette.cyan.cyan2,
  secondary3: colorPalette.cyan.cyan3,
  secondary4: colorPalette.cyan.cyan4,
  secondary5: colorPalette.cyan.cyan5,
  secondary6: colorPalette.cyan.cyan6,
  secondary7: colorPalette.cyan.cyan7,
  secondary8: colorPalette.cyan.cyan8,
  secondary9: colorPalette.cyan.cyan9,
  secondary10: colorPalette.cyan.cyan10,
  secondary11: colorPalette.cyan.cyan11,
  secondary12: colorPalette.cyan.cyan12,

  secondaryA1: colorPalette.cyanA.cyanA1,
  secondaryA2: colorPalette.cyanA.cyanA2,
  secondaryA3: colorPalette.cyanA.cyanA3,
  secondaryA4: colorPalette.cyanA.cyanA4,
  secondaryA5: colorPalette.cyanA.cyanA5,
  secondaryA6: colorPalette.cyanA.cyanA6,
  secondaryA7: colorPalette.cyanA.cyanA7,
  secondaryA8: colorPalette.cyanA.cyanA8,
  secondaryA9: colorPalette.cyanA.cyanA9,
  secondaryA10: colorPalette.cyanA.cyanA10,
  secondaryA11: colorPalette.cyanA.cyanA11,
  secondaryA12: colorPalette.cyanA.cyanA12,

  teritary1: colorPalette.crimson.crimson1,
  teritary2: colorPalette.crimson.crimson2,
  teritary3: colorPalette.crimson.crimson3,
  teritary4: colorPalette.crimson.crimson4,
  teritary5: colorPalette.crimson.crimson5,
  teritary6: colorPalette.crimson.crimson6,
  teritary7: colorPalette.crimson.crimson7,
  teritary8: colorPalette.crimson.crimson8,
  teritary9: colorPalette.crimson.crimson9,
  teritary10: colorPalette.crimson.crimson10,
  teritary11: colorPalette.crimson.crimson11,
  teritary12: colorPalette.crimson.crimson12,

  teritaryA1: colorPalette.crimsonA.crimsonA1,
  teritaryA2: colorPalette.crimsonA.crimsonA2,
  teritaryA3: colorPalette.crimsonA.crimsonA3,
  teritaryA4: colorPalette.crimsonA.crimsonA4,
  teritaryA5: colorPalette.crimsonA.crimsonA5,
  teritaryA6: colorPalette.crimsonA.crimsonA6,
  teritaryA7: colorPalette.crimsonA.crimsonA7,
  teritaryA8: colorPalette.crimsonA.crimsonA8,
  teritaryA9: colorPalette.crimsonA.crimsonA9,
  teritaryA10: colorPalette.crimsonA.crimsonA10,
  teritaryA11: colorPalette.crimsonA.crimsonA11,
  teritaryA12: colorPalette.crimsonA.crimsonA12,

  mono1: colorPalette.gray.gray1,
  mono2: colorPalette.gray.gray2,
  mono3: colorPalette.gray.gray3,
  mono4: colorPalette.gray.gray4,
  mono5: colorPalette.gray.gray5,
  mono6: colorPalette.gray.gray6,
  mono7: colorPalette.gray.gray7,
  mono8: colorPalette.gray.gray8,
  mono9: colorPalette.gray.gray9,
  mono10: colorPalette.gray.gray10,
  mono11: colorPalette.gray.gray11,
  mono12: colorPalette.gray.gray12,

  monoA1: colorPalette.grayA.grayA1,
  monoA2: colorPalette.grayA.grayA2,
  monoA3: colorPalette.grayA.grayA3,
  monoA4: colorPalette.grayA.grayA4,
  monoA5: colorPalette.grayA.grayA5,
  monoA6: colorPalette.grayA.grayA6,
  monoA7: colorPalette.grayA.grayA7,
  monoA8: colorPalette.grayA.grayA8,
  monoA9: colorPalette.grayA.grayA9,
  monoA10: colorPalette.grayA.grayA10,
  monoA11: colorPalette.grayA.grayA11,
  monoA12: colorPalette.grayA.grayA12,

  success1: colorPalette.green.green1,
  success2: colorPalette.green.green2,
  success3: colorPalette.green.green3,
  success4: colorPalette.green.green4,
  success5: colorPalette.green.green5,
  success6: colorPalette.green.green6,
  success7: colorPalette.green.green7,
  success8: colorPalette.green.green8,
  success9: colorPalette.green.green9,
  success10: colorPalette.green.green10,
  success11: colorPalette.green.green11,
  success12: colorPalette.green.green12,

  successA1: colorPalette.greenA.greenA1,
  successA2: colorPalette.greenA.greenA2,
  successA3: colorPalette.greenA.greenA3,
  successA4: colorPalette.greenA.greenA4,
  successA5: colorPalette.greenA.greenA5,
  successA6: colorPalette.greenA.greenA6,
  successA7: colorPalette.greenA.greenA7,
  successA8: colorPalette.greenA.greenA8,
  successA9: colorPalette.greenA.greenA9,
  successA10: colorPalette.greenA.greenA10,
  successA11: colorPalette.greenA.greenA11,
  successA12: colorPalette.greenA.greenA12,

  warning1: colorPalette.orange.orange1,
  warning2: colorPalette.orange.orange2,
  warning3: colorPalette.orange.orange3,
  warning4: colorPalette.orange.orange4,
  warning5: colorPalette.orange.orange5,
  warning6: colorPalette.orange.orange6,
  warning7: colorPalette.orange.orange7,
  warning8: colorPalette.orange.orange8,
  warning9: colorPalette.orange.orange9,
  warning10: colorPalette.orange.orange10,
  warning11: colorPalette.orange.orange11,
  warning12: colorPalette.orange.orange12,

  warningA1: colorPalette.orangeA.orangeA1,
  warningA2: colorPalette.orangeA.orangeA2,
  warningA3: colorPalette.orangeA.orangeA3,
  warningA4: colorPalette.orangeA.orangeA4,
  warningA5: colorPalette.orangeA.orangeA5,
  warningA6: colorPalette.orangeA.orangeA6,
  warningA7: colorPalette.orangeA.orangeA7,
  warningA8: colorPalette.orangeA.orangeA8,
  warningA9: colorPalette.orangeA.orangeA9,
  warningA10: colorPalette.orangeA.orangeA10,
  warningA11: colorPalette.orangeA.orangeA11,
  warningA12: colorPalette.orangeA.orangeA12,

  error1: colorPalette.red.red1,
  error2: colorPalette.red.red2,
  error3: colorPalette.red.red3,
  error4: colorPalette.red.red4,
  error5: colorPalette.red.red5,
  error6: colorPalette.red.red6,
  error7: colorPalette.red.red7,
  error8: colorPalette.red.red8,
  error9: colorPalette.red.red9,
  error10: colorPalette.red.red10,
  error11: colorPalette.red.red11,
  error12: colorPalette.red.red12,

  errorA1: colorPalette.redA.redA1,
  errorA2: colorPalette.redA.redA2,
  errorA3: colorPalette.redA.redA3,
  errorA4: colorPalette.redA.redA4,
  errorA5: colorPalette.redA.redA5,
  errorA6: colorPalette.redA.redA6,
  errorA7: colorPalette.redA.redA7,
  errorA8: colorPalette.redA.redA8,
  errorA9: colorPalette.redA.redA9,
  errorA10: colorPalette.redA.redA10,
  errorA11: colorPalette.redA.redA11,
  errorA12: colorPalette.redA.redA12,

  blue1: colorPalette.blue.blue1,
  blue2: colorPalette.blue.blue2,
  blue3: colorPalette.blue.blue3,
  blue4: colorPalette.blue.blue4,
  blue5: colorPalette.blue.blue5,
  blue6: colorPalette.blue.blue6,
  blue7: colorPalette.blue.blue7,
  blue8: colorPalette.blue.blue8,
  blue9: colorPalette.blue.blue9,
  blue10: colorPalette.blue.blue10,
  blue11: colorPalette.blue.blue11,
  blue12: colorPalette.blue.blue12,

  blueA1: colorPalette.blueA.blueA1,
  blueA2: colorPalette.blueA.blueA2,
  blueA3: colorPalette.blueA.blueA3,
  blueA4: colorPalette.blueA.blueA4,
  blueA5: colorPalette.blueA.blueA5,
  blueA6: colorPalette.blueA.blueA6,
  blueA7: colorPalette.blueA.blueA7,
  blueA8: colorPalette.blueA.blueA8,
  blueA9: colorPalette.blueA.blueA9,
  blueA10: colorPalette.blueA.blueA10,
  blueA11: colorPalette.blueA.blueA11,
  blueA12: colorPalette.blueA.blueA12,

  yellow1: colorPalette.yellow.yellow1,
  yellow2: colorPalette.yellow.yellow2,
  yellow3: colorPalette.yellow.yellow3,
  yellow4: colorPalette.yellow.yellow4,
  yellow5: colorPalette.yellow.yellow5,
  yellow6: colorPalette.yellow.yellow6,
  yellow7: colorPalette.yellow.yellow7,
  yellow8: colorPalette.yellow.yellow8,
  yellow9: colorPalette.yellow.yellow9,
  yellow10: colorPalette.yellow.yellow10,
  yellow11: colorPalette.yellow.yellow11,
  yellow12: colorPalette.yellow.yellow12,

  yellowA1: colorPalette.yellowA.yellowA1,
  yellowA2: colorPalette.yellowA.yellowA2,
  yellowA3: colorPalette.yellowA.yellowA3,
  yellowA4: colorPalette.yellowA.yellowA4,
  yellowA5: colorPalette.yellowA.yellowA5,
  yellowA6: colorPalette.yellowA.yellowA6,
  yellowA7: colorPalette.yellowA.yellowA7,
  yellowA8: colorPalette.yellowA.yellowA8,
  yellowA9: colorPalette.yellowA.yellowA9,
  yellowA10: colorPalette.yellowA.yellowA10,
  yellowA11: colorPalette.yellowA.yellowA11,
  yellowA12: colorPalette.yellowA.yellowA12,

  backgroundPrimary: colorPalette.purple.purple4,
  backgroundSecondary: colorPalette.cyan.cyan4,
  backgroundTeritary: colorPalette.amber.amber4,
  backgroundInversePrimary: colorPalette.purple.purple6,
  backgroundInverseSecondary: colorPalette.cyan.cyan6,
  backgroundInverseTeritary: colorPalette.amber.amber6,
  foregroundPrimary: colorPalette.purple.purple12,
  foregroundSecondary: colorPalette.cyan.cyan12,
  foregroundTeritary: colorPalette.amber.amber12,
  foregroundInversePrimary: colorPalette.purple.purple10,
  foregroundInverseSecondary: colorPalette.cyan.cyan10,
  foregroundInverseTeritary: colorPalette.amber.amber10,
}

export default themeColor
