import colorPalette from '@src/tokens/colorPalette'
import { StitchesColors } from '../types'

// TODO: type auto generate primary, secondary...

const themeColor: StitchesColors = {
  transparent: colorPalette.transparent,
  current: colorPalette.current,
  black: colorPalette.black,
  white: colorPalette.white,

  primary1: colorPalette.purple.purple1,
  primary2: colorPalette.purple.purple2,
  primary3: colorPalette.purple.purple3,
  primary4: colorPalette.purple.purple4,
  primary5: colorPalette.purple.purple5,
  primary6: colorPalette.purple.purple6,
  primary7: colorPalette.purple.purple7,
  primary8: colorPalette.purple.purple8,
  primary9: colorPalette.purple.purple9,
  primary10: colorPalette.purple.purple10,
  primary11: colorPalette.purple.purple11,
  primary12: colorPalette.purple.purple12,

  secondary1: colorPalette.cyan.cyan1,
  secondary2: colorPalette.cyan.cyan2,
  secondary3: colorPalette.cyan.cyan3,
  secondary4: colorPalette.cyan.cyan4,
  secondary5: colorPalette.cyan.cyan5,
  secondary6: colorPalette.cyan.cyan6,
  secondary7: colorPalette.cyan.cyan7,
  secondary8: colorPalette.cyan.cyan8,
  secondary9: colorPalette.cyan.cyan9,
  secondary10: colorPalette.cyan.cyan10,
  secondary11: colorPalette.cyan.cyan11,
  secondary12: colorPalette.cyan.cyan12,

  teritary1: colorPalette.crimson.crimson1,
  teritary2: colorPalette.crimson.crimson2,
  teritary3: colorPalette.crimson.crimson3,
  teritary4: colorPalette.crimson.crimson4,
  teritary5: colorPalette.crimson.crimson5,
  teritary6: colorPalette.crimson.crimson6,
  teritary7: colorPalette.crimson.crimson7,
  teritary8: colorPalette.crimson.crimson8,
  teritary9: colorPalette.crimson.crimson9,
  teritary10: colorPalette.crimson.crimson10,
  teritary11: colorPalette.crimson.crimson11,
  teritary12: colorPalette.crimson.crimson12,

  mono1: colorPalette.gray.gray1,
  mono2: colorPalette.gray.gray2,
  mono3: colorPalette.gray.gray3,
  mono4: colorPalette.gray.gray4,
  mono5: colorPalette.gray.gray5,
  mono6: colorPalette.gray.gray6,
  mono7: colorPalette.gray.gray7,
  mono8: colorPalette.gray.gray8,
  mono9: colorPalette.gray.gray9,
  mono10: colorPalette.gray.gray10,
  mono11: colorPalette.gray.gray11,
  mono12: colorPalette.gray.gray12,

  success1: colorPalette.green.green1,
  success2: colorPalette.green.green2,
  success3: colorPalette.green.green3,
  success4: colorPalette.green.green4,
  success5: colorPalette.green.green5,
  success6: colorPalette.green.green6,
  success7: colorPalette.green.green7,
  success8: colorPalette.green.green8,
  success9: colorPalette.green.green9,
  success10: colorPalette.green.green10,
  success11: colorPalette.green.green11,
  success12: colorPalette.green.green12,

  warning1: colorPalette.orange.orange1,
  warning2: colorPalette.orange.orange2,
  warning3: colorPalette.orange.orange3,
  warning4: colorPalette.orange.orange4,
  warning5: colorPalette.orange.orange5,
  warning6: colorPalette.orange.orange6,
  warning7: colorPalette.orange.orange7,
  warning8: colorPalette.orange.orange8,
  warning9: colorPalette.orange.orange9,
  warning10: colorPalette.orange.orange10,
  warning11: colorPalette.orange.orange11,
  warning12: colorPalette.orange.orange12,

  error1: colorPalette.red.red1,
  error2: colorPalette.red.red2,
  error3: colorPalette.red.red3,
  error4: colorPalette.red.red4,
  error5: colorPalette.red.red5,
  error6: colorPalette.red.red6,
  error7: colorPalette.red.red7,
  error8: colorPalette.red.red8,
  error9: colorPalette.red.red9,
  error10: colorPalette.red.red10,
  error11: colorPalette.red.red11,
  error12: colorPalette.red.red12,

  backgroundPrimary: colorPalette.purple.purple4,
  backgroundSecondary: colorPalette.cyan.cyan4,
  backgroundTeritary: colorPalette.amber.amber4,
  backgroundInversePrimary: colorPalette.purple.purple6,
  backgroundInverseSecondary: colorPalette.cyan.cyan6,
  backgroundInverseTeritary: colorPalette.amber.amber6,
  foregroundPrimary: colorPalette.purple.purple12,
  foregroundSecondary: colorPalette.cyan.cyan12,
  foregroundTeritary: colorPalette.amber.amber12,
  foregroundInversePrimary: colorPalette.purple.purple10,
  foregroundInverseSecondary: colorPalette.cyan.cyan10,
  foregroundInverseTeritary: colorPalette.amber.amber10,
}

export default themeColor
