import colorPalette from '@src/tokens/colorPalette'
import { StitchesColors } from '../types'

// const themeColor: Colors = {
//   transparent: colorPalette.transparent,
//   current: colorPalette.current,
//   black: colorPalette.black,
//   white: colorPalette.white,

//   primary: colorPalette.purpleDark,
//   secondary: colorPalette.cyanDark,
//   teritary: colorPalette.amberDark,

//   mono: colorPalette.grayDark,

//   success: colorPalette.greenDark,
//   warning: colorPalette.orangeDark,
//   error: colorPalette.redDark,

//   background: {
//     primary: colorPalette.mauveDark[50],
//     secondary: colorPalette.mauveDark[200],
//     teritary: colorPalette.mauveDark[400],
//     inversePrimary: colorPalette.grayDark[50],
//     inverseSecondary: colorPalette.grayDark[200],
//     inverseTeritary: colorPalette.grayDark[400],
//   },
//   foreground: {
//     primary: colorPalette.white,
//     secondary: colorPalette.mauveDark[1100],
//     teritary: colorPalette.mauveDark[900],
//     inversePrimary: colorPalette.white,
//     inverseSecondary: colorPalette.grayDark[1100],
//     inverseTeritary: colorPalette.grayDark[900],
//   },
// }
const themeColor: StitchesColors = {
  transparent: colorPalette.transparent,
  current: colorPalette.current,
  black: colorPalette.black,
  white: colorPalette.white,

  primary1: colorPalette.purpleDark.purple1,
  primary2: colorPalette.purpleDark.purple2,
  primary3: colorPalette.purpleDark.purple3,
  primary4: colorPalette.purpleDark.purple4,
  primary5: colorPalette.purpleDark.purple5,
  primary6: colorPalette.purpleDark.purple6,
  primary7: colorPalette.purpleDark.purple7,
  primary8: colorPalette.purpleDark.purple8,
  primary9: colorPalette.purpleDark.purple9,
  primary10: colorPalette.purpleDark.purple10,
  primary11: colorPalette.purpleDark.purple11,
  primary12: colorPalette.purpleDark.purple12,

  secondary1: colorPalette.cyanDark.cyan1,
  secondary2: colorPalette.cyanDark.cyan2,
  secondary3: colorPalette.cyanDark.cyan3,
  secondary4: colorPalette.cyanDark.cyan4,
  secondary5: colorPalette.cyanDark.cyan5,
  secondary6: colorPalette.cyanDark.cyan6,
  secondary7: colorPalette.cyanDark.cyan7,
  secondary8: colorPalette.cyanDark.cyan8,
  secondary9: colorPalette.cyanDark.cyan9,
  secondary10: colorPalette.cyanDark.cyan10,
  secondary11: colorPalette.cyanDark.cyan11,
  secondary12: colorPalette.cyanDark.cyan12,

  teritary1: colorPalette.crimsonDark.crimson1,
  teritary2: colorPalette.crimsonDark.crimson2,
  teritary3: colorPalette.crimsonDark.crimson3,
  teritary4: colorPalette.crimsonDark.crimson4,
  teritary5: colorPalette.crimsonDark.crimson5,
  teritary6: colorPalette.crimsonDark.crimson6,
  teritary7: colorPalette.crimsonDark.crimson7,
  teritary8: colorPalette.crimsonDark.crimson8,
  teritary9: colorPalette.crimsonDark.crimson9,
  teritary10: colorPalette.crimsonDark.crimson10,
  teritary11: colorPalette.crimsonDark.crimson11,
  teritary12: colorPalette.crimsonDark.crimson12,

  mono1: colorPalette.grayDark.gray1,
  mono2: colorPalette.grayDark.gray2,
  mono3: colorPalette.grayDark.gray3,
  mono4: colorPalette.grayDark.gray4,
  mono5: colorPalette.grayDark.gray5,
  mono6: colorPalette.grayDark.gray6,
  mono7: colorPalette.grayDark.gray7,
  mono8: colorPalette.grayDark.gray8,
  mono9: colorPalette.grayDark.gray9,
  mono10: colorPalette.grayDark.gray10,
  mono11: colorPalette.grayDark.gray11,
  mono12: colorPalette.grayDark.gray12,

  success1: colorPalette.greenDark.green1,
  success2: colorPalette.greenDark.green2,
  success3: colorPalette.greenDark.green3,
  success4: colorPalette.greenDark.green4,
  success5: colorPalette.greenDark.green5,
  success6: colorPalette.greenDark.green6,
  success7: colorPalette.greenDark.green7,
  success8: colorPalette.greenDark.green8,
  success9: colorPalette.greenDark.green9,
  success10: colorPalette.greenDark.green10,
  success11: colorPalette.greenDark.green11,
  success12: colorPalette.greenDark.green12,

  warning1: colorPalette.orangeDark.orange1,
  warning2: colorPalette.orangeDark.orange2,
  warning3: colorPalette.orangeDark.orange3,
  warning4: colorPalette.orangeDark.orange4,
  warning5: colorPalette.orangeDark.orange5,
  warning6: colorPalette.orangeDark.orange6,
  warning7: colorPalette.orangeDark.orange7,
  warning8: colorPalette.orangeDark.orange8,
  warning9: colorPalette.orangeDark.orange9,
  warning10: colorPalette.orangeDark.orange10,
  warning11: colorPalette.orangeDark.orange11,
  warning12: colorPalette.orangeDark.orange12,

  error1: colorPalette.redDark.red1,
  error2: colorPalette.redDark.red2,
  error3: colorPalette.redDark.red3,
  error4: colorPalette.redDark.red4,
  error5: colorPalette.redDark.red5,
  error6: colorPalette.redDark.red6,
  error7: colorPalette.redDark.red7,
  error8: colorPalette.redDark.red8,
  error9: colorPalette.redDark.red9,
  error10: colorPalette.redDark.red10,
  error11: colorPalette.redDark.red11,
  error12: colorPalette.redDark.red12,

  backgroundPrimary: colorPalette.purpleDark.purple4,
  backgroundSecondary: colorPalette.cyanDark.cyan4,
  backgroundTeritary: colorPalette.amberDark.amber4,
  backgroundInversePrimary: colorPalette.purpleDark.purple6,
  backgroundInverseSecondary: colorPalette.cyanDark.cyan6,
  backgroundInverseTeritary: colorPalette.amberDark.amber6,
  foregroundPrimary: colorPalette.white,
  foregroundSecondary: colorPalette.cyanDark.cyan12,
  foregroundTeritary: colorPalette.amberDark.amber12,
  foregroundInversePrimary: colorPalette.purpleDark.purple10,
  foregroundInverseSecondary: colorPalette.cyanDark.cyan10,
  foregroundInverseTeritary: colorPalette.amberDark.amber10,
}

export default themeColor
