import colorPalette from '@src/tokens/colorPalette'
import { StitchesColors } from '../types'

// const themeColor: Colors = {
//   transparent: colorPalette.transparent,
//   current: colorPalette.current,
//   black: colorPalette.black,
//   white: colorPalette.white,

//   primary: colorPalette.purpleDark,
//   secondary: colorPalette.cyanDark,
//   teritary: colorPalette.amberDark,

//   mono: colorPalette.grayDark,

//   success: colorPalette.greenDark,
//   warning: colorPalette.orangeDark,
//   error: colorPalette.redDark,

//   background: {
//     primary: colorPalette.mauveDark[50],
//     secondary: colorPalette.mauveDark[200],
//     teritary: colorPalette.mauveDark[400],
//     inversePrimary: colorPalette.grayDark[50],
//     inverseSecondary: colorPalette.grayDark[200],
//     inverseTeritary: colorPalette.grayDark[400],
//   },
//   foreground: {
//     primary: colorPalette.white,
//     secondary: colorPalette.mauveDark[1100],
//     teritary: colorPalette.mauveDark[900],
//     inversePrimary: colorPalette.white,
//     inverseSecondary: colorPalette.grayDark[1100],
//     inverseTeritary: colorPalette.grayDark[900],
//   },
// }
const themeColor: StitchesColors = {
  transparent: colorPalette.transparent,
  current: colorPalette.current,
  black: colorPalette.black,
  white: colorPalette.white,

  primary1: colorPalette.purpleDark.purple1,
  primary2: colorPalette.purpleDark.purple2,
  primary3: colorPalette.purpleDark.purple3,
  primary4: colorPalette.purpleDark.purple4,
  primary5: colorPalette.purpleDark.purple5,
  primary6: colorPalette.purpleDark.purple6,
  primary7: colorPalette.purpleDark.purple7,
  primary8: colorPalette.purpleDark.purple8,
  primary9: colorPalette.purpleDark.purple9,
  primary10: colorPalette.purpleDark.purple10,
  primary11: colorPalette.purpleDark.purple11,
  primary12: colorPalette.purpleDark.purple12,

  primaryA1: colorPalette.purpleDarkA.purpleA1,
  primaryA2: colorPalette.purpleDarkA.purpleA2,
  primaryA3: colorPalette.purpleDarkA.purpleA3,
  primaryA4: colorPalette.purpleDarkA.purpleA4,
  primaryA5: colorPalette.purpleDarkA.purpleA5,
  primaryA6: colorPalette.purpleDarkA.purpleA6,
  primaryA7: colorPalette.purpleDarkA.purpleA7,
  primaryA8: colorPalette.purpleDarkA.purpleA8,
  primaryA9: colorPalette.purpleDarkA.purpleA9,
  primaryA10: colorPalette.purpleDarkA.purpleA10,
  primaryA11: colorPalette.purpleDarkA.purpleA11,
  primaryA12: colorPalette.purpleDarkA.purpleA12,

  secondary1: colorPalette.cyanDark.cyan1,
  secondary2: colorPalette.cyanDark.cyan2,
  secondary3: colorPalette.cyanDark.cyan3,
  secondary4: colorPalette.cyanDark.cyan4,
  secondary5: colorPalette.cyanDark.cyan5,
  secondary6: colorPalette.cyanDark.cyan6,
  secondary7: colorPalette.cyanDark.cyan7,
  secondary8: colorPalette.cyanDark.cyan8,
  secondary9: colorPalette.cyanDark.cyan9,
  secondary10: colorPalette.cyanDark.cyan10,
  secondary11: colorPalette.cyanDark.cyan11,
  secondary12: colorPalette.cyanDark.cyan12,

  secondaryA1: colorPalette.cyanDarkA.cyanA1,
  secondaryA2: colorPalette.cyanDarkA.cyanA2,
  secondaryA3: colorPalette.cyanDarkA.cyanA3,
  secondaryA4: colorPalette.cyanDarkA.cyanA4,
  secondaryA5: colorPalette.cyanDarkA.cyanA5,
  secondaryA6: colorPalette.cyanDarkA.cyanA6,
  secondaryA7: colorPalette.cyanDarkA.cyanA7,
  secondaryA8: colorPalette.cyanDarkA.cyanA8,
  secondaryA9: colorPalette.cyanDarkA.cyanA9,
  secondaryA10: colorPalette.cyanDarkA.cyanA10,
  secondaryA11: colorPalette.cyanDarkA.cyanA11,
  secondaryA12: colorPalette.cyanDarkA.cyanA12,

  teritary1: colorPalette.crimsonDark.crimson1,
  teritary2: colorPalette.crimsonDark.crimson2,
  teritary3: colorPalette.crimsonDark.crimson3,
  teritary4: colorPalette.crimsonDark.crimson4,
  teritary5: colorPalette.crimsonDark.crimson5,
  teritary6: colorPalette.crimsonDark.crimson6,
  teritary7: colorPalette.crimsonDark.crimson7,
  teritary8: colorPalette.crimsonDark.crimson8,
  teritary9: colorPalette.crimsonDark.crimson9,
  teritary10: colorPalette.crimsonDark.crimson10,
  teritary11: colorPalette.crimsonDark.crimson11,
  teritary12: colorPalette.crimsonDark.crimson12,

  teritaryA1: colorPalette.crimsonDarkA.crimsonA1,
  teritaryA2: colorPalette.crimsonDarkA.crimsonA2,
  teritaryA3: colorPalette.crimsonDarkA.crimsonA3,
  teritaryA4: colorPalette.crimsonDarkA.crimsonA4,
  teritaryA5: colorPalette.crimsonDarkA.crimsonA5,
  teritaryA6: colorPalette.crimsonDarkA.crimsonA6,
  teritaryA7: colorPalette.crimsonDarkA.crimsonA7,
  teritaryA8: colorPalette.crimsonDarkA.crimsonA8,
  teritaryA9: colorPalette.crimsonDarkA.crimsonA9,
  teritaryA10: colorPalette.crimsonDarkA.crimsonA10,
  teritaryA11: colorPalette.crimsonDarkA.crimsonA11,
  teritaryA12: colorPalette.crimsonDarkA.crimsonA12,

  mono1: colorPalette.grayDark.gray1,
  mono2: colorPalette.grayDark.gray2,
  mono3: colorPalette.grayDark.gray3,
  mono4: colorPalette.grayDark.gray4,
  mono5: colorPalette.grayDark.gray5,
  mono6: colorPalette.grayDark.gray6,
  mono7: colorPalette.grayDark.gray7,
  mono8: colorPalette.grayDark.gray8,
  mono9: colorPalette.grayDark.gray9,
  mono10: colorPalette.grayDark.gray10,
  mono11: colorPalette.grayDark.gray11,
  mono12: colorPalette.grayDark.gray12,

  monoA1: colorPalette.grayDarkA.grayA1,
  monoA2: colorPalette.grayDarkA.grayA2,
  monoA3: colorPalette.grayDarkA.grayA3,
  monoA4: colorPalette.grayDarkA.grayA4,
  monoA5: colorPalette.grayDarkA.grayA5,
  monoA6: colorPalette.grayDarkA.grayA6,
  monoA7: colorPalette.grayDarkA.grayA7,
  monoA8: colorPalette.grayDarkA.grayA8,
  monoA9: colorPalette.grayDarkA.grayA9,
  monoA10: colorPalette.grayDarkA.grayA10,
  monoA11: colorPalette.grayDarkA.grayA11,
  monoA12: colorPalette.grayDarkA.grayA12,

  success1: colorPalette.greenDark.green1,
  success2: colorPalette.greenDark.green2,
  success3: colorPalette.greenDark.green3,
  success4: colorPalette.greenDark.green4,
  success5: colorPalette.greenDark.green5,
  success6: colorPalette.greenDark.green6,
  success7: colorPalette.greenDark.green7,
  success8: colorPalette.greenDark.green8,
  success9: colorPalette.greenDark.green9,
  success10: colorPalette.greenDark.green10,
  success11: colorPalette.greenDark.green11,
  success12: colorPalette.greenDark.green12,

  successA1: colorPalette.greenDarkA.greenA1,
  successA2: colorPalette.greenDarkA.greenA2,
  successA3: colorPalette.greenDarkA.greenA3,
  successA4: colorPalette.greenDarkA.greenA4,
  successA5: colorPalette.greenDarkA.greenA5,
  successA6: colorPalette.greenDarkA.greenA6,
  successA7: colorPalette.greenDarkA.greenA7,
  successA8: colorPalette.greenDarkA.greenA8,
  successA9: colorPalette.greenDarkA.greenA9,
  successA10: colorPalette.greenDarkA.greenA10,
  successA11: colorPalette.greenDarkA.greenA11,
  successA12: colorPalette.greenDarkA.greenA12,

  warning1: colorPalette.orangeDark.orange1,
  warning2: colorPalette.orangeDark.orange2,
  warning3: colorPalette.orangeDark.orange3,
  warning4: colorPalette.orangeDark.orange4,
  warning5: colorPalette.orangeDark.orange5,
  warning6: colorPalette.orangeDark.orange6,
  warning7: colorPalette.orangeDark.orange7,
  warning8: colorPalette.orangeDark.orange8,
  warning9: colorPalette.orangeDark.orange9,
  warning10: colorPalette.orangeDark.orange10,
  warning11: colorPalette.orangeDark.orange11,
  warning12: colorPalette.orangeDark.orange12,

  warningA1: colorPalette.orangeDarkA.orangeA1,
  warningA2: colorPalette.orangeDarkA.orangeA2,
  warningA3: colorPalette.orangeDarkA.orangeA3,
  warningA4: colorPalette.orangeDarkA.orangeA4,
  warningA5: colorPalette.orangeDarkA.orangeA5,
  warningA6: colorPalette.orangeDarkA.orangeA6,
  warningA7: colorPalette.orangeDarkA.orangeA7,
  warningA8: colorPalette.orangeDarkA.orangeA8,
  warningA9: colorPalette.orangeDarkA.orangeA9,
  warningA10: colorPalette.orangeDarkA.orangeA10,
  warningA11: colorPalette.orangeDarkA.orangeA11,
  warningA12: colorPalette.orangeDarkA.orangeA12,

  error1: colorPalette.redDark.red1,
  error2: colorPalette.redDark.red2,
  error3: colorPalette.redDark.red3,
  error4: colorPalette.redDark.red4,
  error5: colorPalette.redDark.red5,
  error6: colorPalette.redDark.red6,
  error7: colorPalette.redDark.red7,
  error8: colorPalette.redDark.red8,
  error9: colorPalette.redDark.red9,
  error10: colorPalette.redDark.red10,
  error11: colorPalette.redDark.red11,
  error12: colorPalette.redDark.red12,

  errorA1: colorPalette.redDarkA.redA1,
  errorA2: colorPalette.redDarkA.redA2,
  errorA3: colorPalette.redDarkA.redA3,
  errorA4: colorPalette.redDarkA.redA4,
  errorA5: colorPalette.redDarkA.redA5,
  errorA6: colorPalette.redDarkA.redA6,
  errorA7: colorPalette.redDarkA.redA7,
  errorA8: colorPalette.redDarkA.redA8,
  errorA9: colorPalette.redDarkA.redA9,
  errorA10: colorPalette.redDarkA.redA10,
  errorA11: colorPalette.redDarkA.redA11,
  errorA12: colorPalette.redDarkA.redA12,

  blue1: colorPalette.blueDark.blue1,
  blue2: colorPalette.blueDark.blue2,
  blue3: colorPalette.blueDark.blue3,
  blue4: colorPalette.blueDark.blue4,
  blue5: colorPalette.blueDark.blue5,
  blue6: colorPalette.blueDark.blue6,
  blue7: colorPalette.blueDark.blue7,
  blue8: colorPalette.blueDark.blue8,
  blue9: colorPalette.blueDark.blue9,
  blue10: colorPalette.blueDark.blue10,
  blue11: colorPalette.blueDark.blue11,
  blue12: colorPalette.blueDark.blue12,

  blueA1: colorPalette.blueDarkA.blueA1,
  blueA2: colorPalette.blueDarkA.blueA2,
  blueA3: colorPalette.blueDarkA.blueA3,
  blueA4: colorPalette.blueDarkA.blueA4,
  blueA5: colorPalette.blueDarkA.blueA5,
  blueA6: colorPalette.blueDarkA.blueA6,
  blueA7: colorPalette.blueDarkA.blueA7,
  blueA8: colorPalette.blueDarkA.blueA8,
  blueA9: colorPalette.blueDarkA.blueA9,
  blueA10: colorPalette.blueDarkA.blueA10,
  blueA11: colorPalette.blueDarkA.blueA11,
  blueA12: colorPalette.blueDarkA.blueA12,

  yellow1: colorPalette.yellowDark.yellow1,
  yellow2: colorPalette.yellowDark.yellow2,
  yellow3: colorPalette.yellowDark.yellow3,
  yellow4: colorPalette.yellowDark.yellow4,
  yellow5: colorPalette.yellowDark.yellow5,
  yellow6: colorPalette.yellowDark.yellow6,
  yellow7: colorPalette.yellowDark.yellow7,
  yellow8: colorPalette.yellowDark.yellow8,
  yellow9: colorPalette.yellowDark.yellow9,
  yellow10: colorPalette.yellowDark.yellow10,
  yellow11: colorPalette.yellowDark.yellow11,
  yellow12: colorPalette.yellowDark.yellow12,

  yellowA1: colorPalette.yellowDarkA.yellowA1,
  yellowA2: colorPalette.yellowDarkA.yellowA2,
  yellowA3: colorPalette.yellowDarkA.yellowA3,
  yellowA4: colorPalette.yellowDarkA.yellowA4,
  yellowA5: colorPalette.yellowDarkA.yellowA5,
  yellowA6: colorPalette.yellowDarkA.yellowA6,
  yellowA7: colorPalette.yellowDarkA.yellowA7,
  yellowA8: colorPalette.yellowDarkA.yellowA8,
  yellowA9: colorPalette.yellowDarkA.yellowA9,
  yellowA10: colorPalette.yellowDarkA.yellowA10,
  yellowA11: colorPalette.yellowDarkA.yellowA11,
  yellowA12: colorPalette.yellowDarkA.yellowA12,

  backgroundPrimary: colorPalette.purpleDark.purple4,
  backgroundSecondary: colorPalette.cyanDark.cyan4,
  backgroundTeritary: colorPalette.amberDark.amber4,
  backgroundInversePrimary: colorPalette.purpleDark.purple6,
  backgroundInverseSecondary: colorPalette.cyanDark.cyan6,
  backgroundInverseTeritary: colorPalette.amberDark.amber6,
  foregroundPrimary: colorPalette.white,
  foregroundSecondary: colorPalette.cyanDark.cyan12,
  foregroundTeritary: colorPalette.amberDark.amber12,
  foregroundInversePrimary: colorPalette.purpleDark.purple10,
  foregroundInverseSecondary: colorPalette.cyanDark.cyan10,
  foregroundInverseTeritary: colorPalette.amberDark.amber10,
}

export default themeColor
